name: issue-helper

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

permissions:
  issues: write

jobs:
  check-inactive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v11
        with:
          days-before-issue-stale: 100
          days-before-issue-close: 0
          days-before-pr-stale: -1
          days-before-pr-close: -1
          stale-issue-message: ''
          close-issue-message: |
            Hello! your issue has been closed because it has been inactive for a long time.

            你好，你的 issue 因为长时间不活跃而被自动关闭。

            こんにちは、お問い合わせは長期間活動がないため、閉じられました。
